# Required
[hyperbridge]
type = "grandpa"

[hyperbridge.grandpa]
# Hyperbridge's relay chain websocket RPC
rpc = "wss://paseo-rpc.n.dwellir.com"
# Hyperbridge's slot duration
# on Polkadot
# slot_duration = 12000
# on Paseo
slot_duration = 6000
# How frequently to exchange consensus proofs
consensus_update_frequency = 60
# Hyperbridge's paraId on the provided relay chain
# For Paseo Testnet: para_ids = [4009]
# For Polkadot Mainnet: para_ids = [3367]
para_ids = [4009]

[hyperbridge.substrate]
# Hyperbridge's relay chain websocket RPC
rpc_ws = "wss://paseo-rpc.n.dwellir.com"
# Hyperbridge's hashing algorithm
hashing = "Keccak"
# Hyperbridge's consensus state id
# For Paseo Testnet: PAS0
# For Polkadot Mainnet: DOT0
consensus_state_id = "PAS0"
# Hyperbridge's state machine ID
# For Paseo Testnet: KUSAMA-4009
# For Polkadot Mainnet: POLKADOT-3367
state_machine = "KUSAMA-4009"
# Relayer account seed
signer = "0x2b5a65eea607afc816970ee383c05a88fb083d4260bd425211c1788a0efb860a"

# can use any key here
[polkadex]
type = "grandpa"

[polkadex.substrate]
# Solochains's websocket RPC
rpc_ws = "wss://polkadex-testnet.polkadex.ee"
# Hashing can be "Keccak" or "Blake2"
hashing = "Blake2"
# Solochains's consensus state id on Hyperbridge
# should be 4 utf-8 chars chosen by solochain
consensus_state_id = "PDEX"
# Solochains's state machine id. eg
state_machine = "SUBSTRATE-PDEX"
# Relayer account seed
signer = "0x2b5a65eea607afc816970ee383c05a88fb083d4260bd425211c1788a0efb860a"

[polkadex.grandpa]
# Solochains's websocket RPC
rpc = "wss://polkadex-testnet.polkadex.ee"
# Solochains's slot duration
slot_duration = 12000
# How frequently to exchange consensus proofs
consensus_update_frequency = 60
# Any para ids to prove if solochain is actually a relay chain
para_ids = []

[relayer]
maximum_update_intervals = [
    # restart if the polkadot consensus client on your solochain is not updated within 3 minutes
    [{state_id = "KUSAMA-4009", consensus_state_id = "PAS0"}, 180],
    # restart if your solochain consensus client on hyperbridge is not updated within 3 minutes
    [{state_id = "SUBSTRATE-PDEX", consensus_state_id = "PDEX"}, 180],
]