[package]
name = "node-polkadex-runtime"
version = "7.0.0"
authors = ["Polkadex OÜ <https://polkadex.ee>"]
description = "Polkadex Blockchain"
edition = "2021"
license = "GNU GPL v3"
homepage = "https://polkadex.ee"
repository = "https://github.com/Polkadex-Substrate/polkadex-node"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
log = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }
primitive-types = { workspace = true }
parity-scale-codec = { workspace = true, features = ["max-encoded-len"] }
scale-info = { workspace = true, features = ["derive"] }
rust_decimal = { workspace = true }
array-bytes = { workspace = true }
hex-literal = { workspace = true, optional = true }
static_assertions = { workspace = true }

# Pallets
frame-system = { workspace = true }
frame-support = { workspace = true }
frame-executive = { workspace = true }
frame-election-provider-support = { workspace = true }
frame-system-rpc-runtime-api = { workspace = true }
frame-benchmarking = { workspace = true, optional = true }
frame-system-benchmarking = { workspace = true, optional = true }
frame-metadata-hash-extension = { workspace = true }
frame-try-runtime = { workspace = true, optional = true }
pallet-aura = { workspace = true }
pallet-assets = { workspace = true }
pallet-authorship = { workspace = true }
pallet-babe = { workspace = true }
pallet-balances = { workspace = true }
pallet-grandpa = { workspace = true }
pallet-im-online = { workspace = true }
pallet-offences = { workspace = true }
pallet-session = { workspace = true }
pallet-staking = { workspace = true }
pallet-staking-reward-curve = { workspace = true }
pallet-multisig = { workspace = true }
pallet-sudo = { workspace = true }
pallet-utility = { workspace = true }
pallet-timestamp = { workspace = true }
pallet-transaction-payment = { workspace = true }
pallet-transaction-payment-rpc-runtime-api = { workspace = true }
pallet-treasury = { workspace = true }
pallet-collective = { workspace = true }
pallet-democracy = { workspace = true }
pallet-elections-phragmen = { workspace = true }
pallet-membership = { workspace = true }
pallet-scheduler = { workspace = true }
pallet-bounties = { workspace = true }
pallet-preimage = { workspace = true }
pallet-indices = { workspace = true }
pallet-identity = { workspace = true }
pallet-proxy = { workspace = true }
pallet-recovery = { workspace = true }
pallet-election-provider-multi-phase = { workspace = true }
pallet-authority-discovery = { workspace = true }
pallet-child-bounties = { workspace = true }
pallet-statement = { workspace = true }
pallet-asset-tx-payment = { workspace = true }
pallet-society = { workspace = true }
xcm = { workspace = true }
pallet-revive = { workspace = true }
pallet-skip-feeless-payment = { workspace = true }
pallet-contracts = { workspace = true }
pallet-alliance = { workspace = true }
pallet-delegated-staking = { workspace = true }
pallet-insecure-randomness-collective-flip = { workspace = true }
pallet-safe-mode = { workspace = true }
pallet-tx-pause = { workspace = true }
pallet-migrations = { workspace = true }
pallet-mmr = { workspace = true }
pallet-beefy = { workspace = true }
pallet-beefy-mmr = { workspace = true }
pallet-mixnet = { workspace = true }
pallet-staking-runtime-api = { workspace = true }
pallet-asset-conversion = { workspace = true }
pallet-asset-conversion-tx-payment = { workspace = true }
sp-api = { workspace = true }
sp-offchain = { workspace = true }
sp-runtime = { workspace = true }
sp-session = { workspace = true }
sp-std = { workspace = true }
sp-transaction-pool = { workspace = true }
sp-version = { workspace = true }
sp-io = { workspace = true }
sp-statement-store = { workspace = true }
sp-storage = { workspace = true, optional = true }
sp-consensus-aura = { workspace = true }
sp-consensus-babe = { workspace = true }
sp-consensus-beefy = { workspace = true }
sp-consensus-grandpa = { workspace = true }
sp-mixnet = { workspace = true }
sp-genesis-builder = { workspace = true }
sp-keyring = { workspace = true }
sp-authority-discovery = { workspace = true }
sp-block-builder = { workspace = true }
sp-core = { workspace = true }
sp-inherents = { workspace = true }
sp-staking = { workspace = true }
sp-npos-elections = { workspace = true }
ismp = { workspace = true }
pallet-ismp = { workspace = true, features = ["unsigned"] }
ismp-parachain = { workspace = true }
ismp-grandpa = { workspace = true }
pallet-ismp-runtime-api = { workspace = true }
pallet-hyperbridge = { workspace = true }
pallet-token-gateway = { workspace = true }

# CUSTOM
polkadex-primitives = { workspace = true }
orderbook-primitives = { workspace = true }
pdex-migration = { workspace = true }
pallet-ocex-lmp = { workspace = true }
pallet-lmp = { workspace = true }
thea = { workspace = true }
pallet-rewards = { workspace = true }
rpc-assets-runtime-api = { workspace = true }
pallet-rewards-runtime-api = { workspace = true }
pallet-ocex-runtime-api = { workspace = true }

[build-dependencies]
substrate-wasm-builder = { workspace = true }
docify = { workspace = true }

[features]
default = ["std"]
# Enable the metadata hash generation.
# This is hidden behind a feature because it increases the compile time.
# The wasm binary needs to be compiled twice, once to fetch the metadata,
# generate the metadata hash and then a second time with the
# `RUNTIME_METADATA_HASH` environment variable set for the `CheckMetadataHash`
# extension.
metadata-hash = ["substrate-wasm-builder/metadata-hash"]
# A convenience feature for enabling things when doing a build
# for an on-chain release.
on-chain-release-build = ["metadata-hash"]

std = [
	"log/std",
	"anyhow/std",
	"serde_json/std",
	"primitive-types/serde",
	"primitive-types/std",
	"parity-scale-codec/std",
	"scale-info/std",
	"rust_decimal/std",
	"frame-metadata-hash-extension/std",
	"pallet-authorship/std",
	"pallet-babe/std",
	"pallet-balances/std",
	"pallet-grandpa/std",
	"pallet-aura/std",
	"pallet-im-online/std",
	"pallet-offences/std",
	"pallet-session/std",
	"pallet-staking/std",
	"pallet-multisig/std",
	"pallet-sudo/std",
	"pallet-utility/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-treasury/std",
	"pallet-collective/std",
	"pallet-democracy/std",
	"pallet-elections-phragmen/std",
	"pallet-membership/std",
	"pallet-scheduler/std",
	"pallet-bounties/std",
	"pallet-preimage/std",
	"pallet-indices/std",
	"pallet-identity/std",
	"pallet-proxy/std",
	"pallet-recovery/std",
	"pallet-election-provider-multi-phase/std",
	"pallet-authority-discovery/std",
	"pallet-child-bounties/std",
	"frame-support/std",
	"frame-system/std",
	"frame-executive/std",
	"sp-api/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",
	"sp-io/std",
	"sp-authority-discovery/std",
	"sp-block-builder/std",
	"sp-consensus-babe/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-staking/std",
	"sp-npos-elections/std",
	"frame-election-provider-support/std",
	"pallet-assets/std",
	"frame-system-rpc-runtime-api/std",
	"polkadex-primitives/std",
	"pdex-migration/std",
	"pallet-ocex-lmp/std",
	"pallet-ocex-runtime-api/std",
	"rpc-assets-runtime-api/std",
	"pallet-rewards-runtime-api/std",
	"thea/std",
	"pallet-rewards/std",
	"frame-try-runtime?/std",
	"orderbook-primitives/std",
	"pallet-asset-conversion/std",
	"pallet-asset-conversion-tx-payment/std",
	"frame-system-benchmarking?/std",
	"pallet-asset-tx-payment/std",
	"pallet-statement/std",
	"sp-statement-store/std",
	"sp-storage?/std",
	"xcm/std",
	"pallet-revive/std",
	"pallet-skip-feeless-payment/std",
	"pallet-contracts/std",
	"pallet-alliance/std",
	"pallet-delegated-staking/std",
	"pallet-insecure-randomness-collective-flip/std",
	"pallet-safe-mode/std",
	"pallet-tx-pause/std",
	"pallet-migrations/std",
	"pallet-mmr/std",
	"pallet-beefy/std",
	"pallet-beefy-mmr/std",
	"sp-consensus-grandpa/std",
	"pallet-mixnet/std",
	"sp-mixnet/std",
	"pallet-staking-runtime-api/std",
	"sp-genesis-builder/std",
	"sp-consensus-aura/std",
	"sp-keyring/std",
	"pallet-society/std",
	"ismp/std",
	"pallet-ismp/std",
	"ismp-parachain/std",
	"ismp-grandpa/std",
	"pallet-ismp-runtime-api/std",
	"pallet-hyperbridge/std",
	"pallet-token-gateway/std",
]
runtime-benchmarks = [
	"sp-storage",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"frame-benchmarking/runtime-benchmarks",
	"frame-system-benchmarking/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"hex-literal",
	"pallet-assets/runtime-benchmarks",
	"pallet-collective/runtime-benchmarks",
	"pallet-ocex-lmp/runtime-benchmarks",
	"pdex-migration/runtime-benchmarks",
	"pallet-rewards/runtime-benchmarks",
	"pallet-lmp/runtime-benchmarks",
	"pallet-asset-conversion/runtime-benchmarks",
	"pallet-asset-tx-payment/runtime-benchmarks",
	"pallet-migrations/runtime-benchmarks",
]

try-runtime = [
	"frame-executive/try-runtime",
	"frame-try-runtime/try-runtime",
	"frame-system/try-runtime",
	"pallet-utility/try-runtime",
	"pallet-babe/try-runtime",
	"pallet-timestamp/try-runtime",
	"pallet-authorship/try-runtime",
	"pallet-indices/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-transaction-payment/try-runtime",
	"pallet-election-provider-multi-phase/try-runtime",
	"pallet-staking/try-runtime",
	"pallet-session/try-runtime",
	"pallet-collective/try-runtime",
	"pallet-elections-phragmen/try-runtime",
	"pallet-membership/try-runtime",
	"pallet-grandpa/try-runtime",
	"pallet-aura/try-runtime",
	"pallet-treasury/try-runtime",
	"pallet-sudo/try-runtime",
	"pallet-im-online/try-runtime",
	"pallet-authority-discovery/try-runtime",
	"pallet-offences/try-runtime",
	"pallet-identity/try-runtime",
	"pallet-recovery/try-runtime",
	"pallet-scheduler/try-runtime",
	"pallet-proxy/try-runtime",
	"pallet-multisig/try-runtime",
	"pallet-bounties/try-runtime",
	"pdex-migration/try-runtime",
	"pallet-democracy/try-runtime",
	"pallet-preimage/try-runtime",
	"pallet-child-bounties/try-runtime",
	"pallet-assets/try-runtime",
	"pallet-ocex-lmp/try-runtime",
	"pallet-lmp/try-runtime",
	"pallet-rewards/try-runtime",
	"pallet-asset-conversion/try-runtime",
	"pallet-asset-conversion-tx-payment/try-runtime",
	"pallet-statement/try-runtime",
	"pallet-asset-tx-payment/try-runtime",
	"pallet-migrations/try-runtime",
	"pallet-revive/try-runtime",
]
