
//! Autogenerated weights for `pallet_token_gateway`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-04-28, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `alchemist`, CPU: `AMD Ryzen 7 5800H with Radeon Graphics`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// ./target/release/polkadex-node
// benchmark
// pallet
// --runtime
// ./target/release/wbuild/node-polkadex-runtime/node_polkadex_runtime.compact.compressed.wasm
// --genesis-builder=runtime
// --pallet
// pallet_token_gateway
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// runtimes/mainnet/src/weights/pallet_token_gateway.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_token_gateway`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_token_gateway::WeightInfo for WeightInfo<T> {
	/// Storage: `TokenGateway::Precisions` (r:0 w:100)
	/// Proof: `TokenGateway::Precisions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TokenGateway::NativeAssets` (r:0 w:1)
	/// Proof: `TokenGateway::NativeAssets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TokenGateway::LocalAssets` (r:0 w:1)
	/// Proof: `TokenGateway::LocalAssets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TokenGateway::SupportedAssets` (r:0 w:1)
	/// Proof: `TokenGateway::SupportedAssets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `x` is `[1, 100]`.
	fn create_erc6160_asset(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 18_494_000 picoseconds.
		// Scaled 1.7x for Xeon Platinum 8375C @ 2.90GHz (benchmarked on Ryzen 7 5800H @ 4.46GHz)
		Weight::from_parts(29_090_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 5_874
			.saturating_add(Weight::from_parts(4_166_000, 0).saturating_mul(x.into()))
			.saturating_add(T::DbWeight::get().writes(3))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(x.into())))
	}
	/// Storage: `TokenGateway::SupportedAssets` (r:1 w:0)
	/// Proof: `TokenGateway::SupportedAssets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TokenGateway::NativeAssets` (r:1 w:0)
	/// Proof: `TokenGateway::NativeAssets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `TokenGateway::Precisions` (r:1 w:0)
	/// Proof: `TokenGateway::Precisions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Hyperbridge::HostParams` (r:1 w:0)
	/// Proof: `Hyperbridge::HostParams` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Ismp::Nonce` (r:1 w:1)
	/// Proof: `Ismp::Nonce` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473b1f563a105007c434194bddd6a22` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e7473b1f563a105007c434194bddd6a22` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x526571756573745061796d656e74b1f563a105007c434194bddd6a2289e9cee4` (r:0 w:1)
	/// Proof: UNKNOWN KEY `0x526571756573745061796d656e74b1f563a105007c434194bddd6a2289e9cee4` (r:0 w:1)
	fn teleport() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `585`
		//  Estimated: `4050`
		// Minimum execution time: 100_874_000 picoseconds.
		// Scaled 1.7x for Xeon Platinum 8375C @ 2.90GHz (benchmarked on Ryzen 7 5800H @ 4.46GHz)
		Weight::from_parts(175_950_000, 0)
			.saturating_add(Weight::from_parts(0, 4050))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `TokenGateway::TokenGatewayAddresses` (r:0 w:1)
	/// Proof: `TokenGateway::TokenGatewayAddresses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `x` is `[1, 100]`.
	fn set_token_gateway_addresses(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 7_213_000 picoseconds.
		// Scaled 1.7x for Xeon Platinum 8375C @ 2.90GHz (benchmarked on Ryzen 7 5800H @ 4.46GHz)
		Weight::from_parts(13_327_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 333
			.saturating_add(Weight::from_parts(2_222, 0).saturating_mul(x.into()))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `TokenGateway::Precisions` (r:0 w:100)
	/// Proof: `TokenGateway::Precisions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `x` is `[1, 100]`.
	fn update_asset_precision(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 7_444_000 picoseconds.
		// Scaled 1.7x for Xeon Platinum 8375C @ 2.90GHz (benchmarked on Ryzen 7 5800H @ 4.46GHz)
		Weight::from_parts(12_824_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 9_770
			.saturating_add(Weight::from_parts(4_521_000, 0).saturating_mul(x.into()))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(x.into())))
	}
	fn update_erc6160_asset() -> Weight {
		// Scaled 1.7x for Xeon Platinum 8375C @ 2.90GHz (benchmarked on Ryzen 7 5800H @ 4.46GHz)
		Weight::from_parts(17_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	fn register_asset_locally(_p: u32) -> Weight {
		// Scaled 1.7x for Xeon Platinum 8375C @ 2.90GHz (benchmarked on Ryzen 7 5800H @ 4.46GHz)
		Weight::from_parts(17_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
