[package]
name = "polkadex-node"
version = "7.0.0"
authors = ["Polkadex OÜ <https://polkadex.ee>"]
description = "Polkadex Blockchain"
edition = "2021"
license = "GNU GPL v3"
build = "build.rs"
homepage = "https://polkadex.ee"
repository = "https://github.com/Polkadex-Substrate/polkadex-node"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
substrate-build-script-utils = { workspace = true }

[dependencies]
log = { workspace = true }
rand = { workspace = true }
array-bytes = { workspace = true }
docify = { workspace = true }
hex-literal = { workspace = true }
parity-scale-codec = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
futures = { workspace = true }
clap = { workspace = true }
itertools = { workspace = true }
jsonrpsee = { workspace = true, features = ["server"] }
staging-node-inspect = { workspace = true }
frame-system = { workspace = true }
frame-system-rpc-runtime-api = { workspace = true }
frame-support = { workspace = true }
frame-metadata-hash-extension = { workspace = true }
frame-benchmarking-cli = { workspace = true }
frame-benchmarking = { workspace = true, optional = true }
frame-try-runtime = { workspace = true, optional = true }
pallet-im-online = { workspace = true }
pallet-transaction-payment-rpc = { workspace = true }
sc-basic-authorship = { workspace = true }
sc-cli = { workspace = true }
sc-client-api = { workspace = true }
sc-chain-spec = { workspace = true }
sc-consensus = { workspace = true }
sc-consensus-slots = { workspace = true }
sc-consensus-babe = { workspace = true }
sc-consensus-babe-rpc = { workspace = true }
sc-consensus-grandpa = { workspace = true }
sc-consensus-grandpa-rpc = { workspace = true }
sc-consensus-beefy = { workspace = true }
sc-consensus-beefy-rpc = { workspace = true }
sc-sync-state-rpc = { workspace = true }
sc-authority-discovery = { workspace = true }
sc-network = { workspace = true }
# sc-network-types = { workspace = true }
sc-network-sync = { workspace = true }
sc-network-statement = { workspace = true }
sc-mixnet = { workspace = true }
sc-storage-monitor = { workspace = true }
sc-sysinfo = { workspace = true }
sc-rpc = { workspace = true }
sc-rpc-api = { workspace = true }
sc-transaction-pool = { workspace = true }
sc-transaction-pool-api = { workspace = true }
sc-offchain = { workspace = true }
sc-telemetry = { workspace = true }
sc-statement-store = { workspace = true }
sc-executor = { workspace = true }
sc-service = { workspace = true }
sp-io = { workspace = true }
sp-api = { workspace = true }
sp-block-builder = { workspace = true }
sp-blockchain = { workspace = true }
sp-consensus = { workspace = true }
sp-consensus-babe = { workspace = true }
sp-consensus-grandpa = { workspace = true }
sp-consensus-aura = { workspace = true }
sp-consensus-beefy = { workspace = true }
sp-core = { workspace = true }
sp-keystore = { workspace = true }
sp-inherents = { workspace = true }
sp-timestamp = { workspace = true }
sp-runtime = { workspace = true }
sp-keyring = { workspace = true }
sp-authority-discovery = { workspace = true }
sp-statement-store = { workspace = true }
sp-application-crypto = { workspace = true }
sp-transaction-storage-proof = { workspace = true }
sp-mixnet = { workspace = true }
sp-mmr-primitives = { workspace = true }
sp-genesis-builder = { workspace = true }
pallet-beefy = { workspace = true }
pallet-society = { workspace = true }
pallet-skip-feeless-payment = { workspace = true }
pallet-asset-conversion = { workspace = true }
pallet-asset-conversion-tx-payment = { workspace = true }
pallet-ismp-runtime-api = { workspace = true }
substrate-state-trie-migration-rpc = { workspace = true }
substrate-frame-rpc-system = { workspace = true }
mmr-rpc = { workspace = true }
mmr-gadget = { workspace = true }
cumulus-client-service = { workspace = true }
cumulus-client-consensus-common = { workspace = true }
cumulus-client-consensus-aura = { workspace = true }

# CUSTOM
node-polkadex-runtime = { workspace = true }
rpc-assets = { workspace = true }
pallet-rewards-rpc = { workspace = true }
pallet-ocex-rpc = { workspace = true }
polkadex-client = { workspace = true }
thea = { workspace = true }
pallet-ocex-lmp = { workspace = true }
swap-rpc = { workspace = true }
ismp-rpc = { workspace =  true }
polkadex-primitives = { workspace = true }
bls-primitives = { workspace = true }

[dev-dependencies]
futures = { workspace = true }

[features]
default = []
runtime-benchmarks = ["node-polkadex-runtime/runtime-benchmarks", "frame-benchmarking-cli/runtime-benchmarks", "frame-benchmarking"]
try-runtime = ["node-polkadex-runtime/try-runtime"]
