[package]
name = "polkadex-node"
version = "6.2.0"
authors = ["Polkadex OÜ <https://polkadex.trade>"]
description = "Polkadex main blockchain"
edition = "2021"
license = "GNU GPL v3"
build = "build.rs"
homepage = "https://polkadex.trade"
repository = "https://github.com/Polkadex-Substrate/Polkadex/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
substrate-build-script-utils = { version = "11.0.0" }
structopt = { version = "0.3.8", optional = true }

[dependencies]
# third-party dependencies
rand = { workspace = true, default-features = false }
array-bytes = { workspace = true, default-features = false }
log = { workspace = true, default-features = false }
serde_json = { workspace = true, default-features = false, features = ["alloc"] }
docify = { workspace = true }
codec = { package = "parity-scale-codec", version = "3.0.0" }
serde = { version = "1.0.136", features = ["derive"] }
futures = { version = "0.3.9", features = ["compat"] }
hex-literal = "0.4.1"
clap = { version = "4.0.9", features = ["derive"] }
itertools = "0.10.1"
# jsonrpsee = { version = "0.16.2", features = ["server"] }
jsonrpsee = { features = ["server"], workspace = true }
# local dependencies
node-polkadex-runtime = { path = "../../runtimes/mainnet"}
rpc-assets = { path = "../../rpc/assets" }
ismp-rpc = { path = "../../rpc/ismp" }
pallet-rewards-rpc = { path = "../../pallets/rewards/rpc" }
pallet-ocex-rpc = { path = "../../pallets/ocex/rpc" }
polkadex-client = { path = "../../client" }
thea = { path = "../../pallets/thea" }
pallet-ocex-lmp = { path = "../../pallets/ocex" }
swap-rpc = { path = "../../rpc/swap" }
staging-node-inspect = { workspace = true, default-features = false }
pallet-society = { workspace = true, default-features = false }

# Substrate dependencies
frame-metadata-hash-extension = { version = "0.8.0" }
frame-support = { version = "40.1.0" }
frame-benchmarking-cli = { version = "48.0.0" }
pallet-im-online = { version = "39.1.0" }
pallet-transaction-payment-rpc = { version = "43.0.0" }
sc-basic-authorship = { version = "0.49.0" }
sc-client-api = { version = "39.0.0" }
sc-chain-spec = { version = "43.0.0" }
sc-consensus = { version = "0.49.0" }
sc-sync-state-rpc = { version = "0.50.0" }
sc-consensus-slots = { version = "0.49.0" }
sc-authority-discovery = { version = "0.50.0" }
sc-consensus-babe = { version = "0.50.0" }
sc-consensus-babe-rpc = { version = "0.50.0" }
grandpa = { version = "0.35.0", package = "sc-consensus-grandpa" }
sc-consensus-grandpa-rpc = { version = "0.35.0" }
sc-network = { version = "0.50.0" }
# sc-network-types = { version = "0.16.0" }
sc-mixnet = { workspace = true, default-features = false }
sc-storage-monitor = { version = "0.24.0" }
sc-sysinfo = { version = "42.0.0" }
sc-network-sync = { version = "0.49.0" }
sc-rpc = { version = "45.0.0" }
sc-rpc-api = { version = "0.49.0" }
sc-transaction-pool = { version = "39.0.0" }
sp-io = { workspace = true, default-features = false }
sp-api = { version = "36.0.1" }
sp-block-builder = { version = "36.0.0" }
sp-blockchain = { version = "39.0.0" }
sp-consensus = { version = "0.42.0" }
sp-consensus-babe = { version = "0.42.1" }
sc-offchain = { version = "45.0.0" }
sp-core = { version = "36.1.0" }
sp-keystore = { version = "0.42.0" }
grandpa-primitives = { version = "23.1.0", package = "sp-consensus-grandpa" }
sp-inherents = { version = "36.0.0" }
sp-timestamp = { version = "36.0.0" }
sp-runtime = { version = "41.1.0" }
sc-telemetry = { version = "28.1.0" }
substrate-frame-rpc-system = { version = "44.0.0" }
sp-keyring = { version = "41.0.0" }
frame-system = { version = "40.2.0" }
sc-transaction-pool-api = { version = "39.0.0" }
sp-authority-discovery = { version = "36.0.0" }
sc-statement-store = { version = "21.0.0" }
sp-statement-store = { version = "20.1.0" }
sc-network-statement = { version = "0.32.0" }
pallet-asset-conversion-tx-payment = { version = "22.0.0" }
pallet-asset-conversion = { version = "22.0.0" }
sp-application-crypto = { workspace = true, default-features = false }
sp-consensus-aura = { workspace = true, default-features = false }
sc-consensus-beefy-rpc = { workspace = true, default-features = false }
substrate-state-trie-migration-rpc = { workspace = true, default-features = false }
pallet-skip-feeless-payment = { workspace = true, default-features = false }
##Primitives
polkadex-primitives = { path = "../../primitives/polkadex" }
sc-executor = { version = "0.42.0" }
sc-cli = { version = "0.52.0" }
sc-service = { version = "0.51.0" }
sc-consensus-beefy = { workspace = true, default-features = false }
sp-consensus-beefy = { workspace = true, default-features = false }
sp-transaction-storage-proof = { version = "36.1.0" }
frame-try-runtime = { version = "0.46.0", optional = true }
# try-runtime-cli = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.1.0", optional = true }
try-runtime-cli = { version = "0.42.0", default-features = false, optional = true }
mmr-rpc = { workspace = true, default-features = false }
mmr-gadget = { workspace = true, default-features = false }
frame-system-rpc-runtime-api = { default-features = false, workspace = true }
sp-mixnet = { workspace = true, default-features = false }
sp-mmr-primitives = { workspace = true, default-features = false }
pallet-beefy = { workspace = true, default-features = false }
sp-genesis-builder = { workspace = true, default-features = false }

# Cumulus
cumulus-client-service = { version = "0.24.0" }
cumulus-client-consensus-common = { version = "0.23.0" }
cumulus-client-consensus-aura = { workspace = true, default-features = false }

# ismp
pallet-ismp-runtime-api = { workspace = true }
# pallet-ismp-rpc = { workspace = true, default-features = false }

[dev-dependencies]
futures = "0.3.9"
#tempfile = "3.1.0"
#sc-consensus = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0" }
#sc-consensus-babe = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0" }
#sc-consensus-epochs = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0" }
#sp-tracing = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0" }
#sc-service-test = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0"}

[features]
default = []
runtime-benchmarks = ["node-polkadex-runtime/runtime-benchmarks", "frame-benchmarking-cli/runtime-benchmarks"]
try-runtime = ["node-polkadex-runtime/try-runtime", "try-runtime-cli/try-runtime", "try-runtime-cli"]
